### PR TITLE
Fixes #1, #2. Partially implements #3, #4.

### LINKED ISSUE #1: Needs to be updated for new macros 1.1 semantics
Should be as simple as leaving `#ast` out of the resulting TokenStream.

### PR DESCRIPTION
**Pull request by Arnavion**

### CODE REVIEW

**Comment by emk** [comment]
Wow, this looks great! I'm travelling today but I hope to merge a bunch of PRs tomorrow with any luck. I'll take a look at this then and review/merge it. Thank you so much!

**Comment by Arnavion** [comment]
I've removed the commit to emit `#[allow(missing_docs)]` for now based on the discussion in #4.

**Comment by lucab** [comment]
Bump. Any update on this?

**Comment by emk** [comment]
OK, I'm added an assignee, so I should keep better track of this. I was busy with travel and _other_ Rust projects... Thank you for the PR!

**Comment by Arnavion** [comment]
:birthday:

**Comment by Arnavion** [comment]
I've sworn off trivial getters entirely so I no longer need this.

**Pull request closed without merging**
